# Generated by Django 3.2.4 on 2021-07-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자명')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('school', models.CharField(max_length=64, verbose_name='학교')),
                ('major', models.CharField(max_length=64, verbose_name='학과')),
                ('grade', models.CharField(max_length=64, verbose_name='학년')),
                ('phone', models.CharField(max_length=64, verbose_name='전화번호')),
                ('register_dttm', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
            options={
                'verbose_name': '사용자 모임',
                'verbose_name_plural': '사용자 모임',
                'db_table': 'user_define_fuser_table',
            },
        ),
    ]
